apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: neutrino-api
          command:
            - "uvicorn"
          args: [
                "app.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "80",
                "--log-level",
                "info",
                "--workers",
                "1",
              ]
          resources:
            requests:
              memory: "16Mi"
              cpu: "20m"

          ports: 
            - containerPort: 80
              name: http
            - containerPort: 10008
              name: debug

          envFrom:
            - configMapRef:
                name: api-config

        